#!/bin/sh
#
# Start the network....
#

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

case "$1" in
  start)
 	echo "Starting network..."
	/sbin/ifup -a
	ifconfig eth0 promisc
	echo 1 > /proc/sys/net/ipv4/ip_forward
	echo ff > /sys/class/net/eth0/queues/rx-0/rps_cpus
	echo ff > /sys/class/net/eth0/queues/rx-1/rps_cpus
	echo ff > /sys/class/net/eth0/queues/rx-2/rps_cpus
	echo ff > /sys/class/net/eth0/queues/rx-3/rps_cpus
	echo ff > /sys/class/net/eth0/queues/rx-4/rps_cpus
	echo ff > /sys/class/net/eth0/queues/rx-5/rps_cpus
	echo ff > /sys/class/net/eth0/queues/rx-6/rps_cpus
	echo ff > /sys/class/net/eth0/queues/rx-7/rps_cpus
	;;
  stop)
	printf "Stopping network..."
	/sbin/ifdown -a
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

